// GENERATED by prd2mcp from spec.json. DO NOT EDIT.
import { z } from "zod";

export const name = "create_note";
export const config = {
  title: "Create note",
  description: "Create a new note with a title and body. Returns the created note.",
  inputSchema: {
    title: z.string().min(1).max(200).describe("Short title for the note"),
    body: z.string().max(10_000).describe("Body text of the note"),
  },
  outputSchema: {
    id: z.string(),
    title: z.string(),
    body: z.string(),
    createdAt: z.string(),
  },
};
export type Input = z.infer<z.ZodObject<typeof config.inputSchema>>;
