// GENERATED by prd2mcp from spec.json. DO NOT EDIT.
import { z } from "zod";

export const name = "delete_note";
export const config = {
  title: "Delete note",
  description: "Delete a note by its id.",
  inputSchema: {
    id: z.string().describe("Id of the note"),
  },
  outputSchema: {
    deleted: z.boolean(),
  },
};
export type Input = z.infer<z.ZodObject<typeof config.inputSchema>>;
