// GENERATED by prd2mcp from spec.json. DO NOT EDIT.
import { z } from "zod";

export const name = "get_note";
export const config = {
  title: "Get note",
  description: "Fetch a single note by its id.",
  inputSchema: {
    id: z.string().describe("Id of the note"),
  },
  outputSchema: {
    id: z.string(),
    title: z.string(),
    body: z.string(),
    createdAt: z.string(),
  },
};
export type Input = z.infer<z.ZodObject<typeof config.inputSchema>>;
