// GENERATED by prd2mcp from spec.json. DO NOT EDIT.
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { Ctx } from "../lib/context.js";
import * as createNote from "./create_note.schema.js";
import { handler as createNoteHandler } from "./create_note.handler.js";
import * as listNotes from "./list_notes.schema.js";
import { handler as listNotesHandler } from "./list_notes.handler.js";
import * as getNote from "./get_note.schema.js";
import { handler as getNoteHandler } from "./get_note.handler.js";
import * as deleteNote from "./delete_note.schema.js";
import { handler as deleteNoteHandler } from "./delete_note.handler.js";

export const serverInfo = { name: "notes", version: "0.1.0" };
export const toolNames = ["create_note", "list_notes", "get_note", "delete_note"] as const;

export function registerAll(server: McpServer, ctx: Ctx): void {
  server.registerTool(createNote.name, createNote.config, (input) => createNoteHandler(input, ctx));
  server.registerTool(listNotes.name, listNotes.config, (input) => listNotesHandler(input, ctx));
  server.registerTool(getNote.name, getNote.config, (input) => getNoteHandler(input, ctx));
  server.registerTool(deleteNote.name, deleteNote.config, (input) => deleteNoteHandler(input, ctx));
}
