// GENERATED by prd2mcp from spec.json. DO NOT EDIT.
import { z } from "zod";

export const name = "list_notes";
export const config = {
  title: "List notes",
  description: "List all notes currently stored, oldest first.",
  inputSchema: {},
  outputSchema: {
    notes: z.array(
      z.object({
        id: z.string(),
        title: z.string(),
        body: z.string(),
        createdAt: z.string(),
      }),
    ),
  },
};
export type Input = z.infer<z.ZodObject<typeof config.inputSchema>>;
