// GENERATED by prd2mcp from spec.json. DO NOT EDIT. (Placeholder in the template.)
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { Ctx } from "../lib/context.js";

export const serverInfo = { name: "template", version: "0.0.0" };
export const toolNames: readonly string[] = [];

export function registerAll(_server: McpServer, _ctx: Ctx): void {}
