// GENERATED by prd2mcp from spec.json. DO NOT EDIT.
import { describe, expect, it } from "vitest";
import { connect, data, textOf } from "./helpers.js";

describe("create_note (spec examples)", () => {
  it("example 1: ok", async () => {
    const client = await connect();
    const r = await client.callTool({ name: "create_note", arguments: { title: "a", body: "b" } });
    expect(r.isError).toBeFalsy();
    expect(data(r)).toMatchObject({ title: "a", body: "b" });
  });

  it("example 2: error", async () => {
    const client = await connect();
    const r = await client.callTool({ name: "create_note", arguments: { title: "", body: "x" } });
    expect(r.isError).toBe(true);
    expect(textOf(r)).toContain("Input validation error");
  });
});
