// GENERATED by prd2mcp from spec.json. DO NOT EDIT.
import { describe, expect, it } from "vitest";
import { connect, textOf } from "./helpers.js";

describe("get_note (spec examples)", () => {
  it("example 1: error", async () => {
    const client = await connect();
    const r = await client.callTool({ name: "get_note", arguments: { id: "nope" } });
    expect(r.isError).toBe(true);
    expect(textOf(r)).toContain("Note not found");
  });
});
