// GENERATED by prd2mcp from spec.json. DO NOT EDIT.
import { describe, expect, it } from "vitest";
import { connect, data } from "./helpers.js";

describe("list_notes (spec examples)", () => {
  it("example 1: ok", async () => {
    const client = await connect();
    const r = await client.callTool({ name: "list_notes", arguments: {} });
    expect(r.isError).toBeFalsy();
    expect(data(r)).toMatchObject({ notes: [] });
  });
});
